require "options"
require "keymaps"
require "plugins"
require "autocommands"
require "comment"
require "colorscheme"
require "autopairs"
require "telescope"

-- require "impatient"
-- require "whichkey"
-- require "tree"
require "lsp"
