require "options"
require "keymaps"
require "plugins"
-- require "autocommands"
-- require "colorscheme"
-- require "telescope"
-- require "autopairs"
-- require "comment"
-- require "bufferline"
-- require "lualine"
-- require "toggleterm"
-- require "impatient"
-- require "whichkey"
-- require "tree"
-- require "lsp"
